function [trainedModel, trainInfo] = trainModel(model, dataTrain, dataVal)
    % trainModel.m
    % This function configures and conducts the training of the deep learning
    % model for mobile robot navigation using multiple sensors' data.
    % It returns the trained model and training information.

    disp('Configuring training options...');
    
    %% Configure Training Options
    options = trainingOptions('adam', ...
        'InitialLearnRate', 1e-4, ...
        'MaxEpochs', 30, ...
        'MiniBatchSize', 32, ...
        'Shuffle', 'every-epoch', ...
        'ValidationData', dataVal, ...
        'ValidationFrequency', 30, ...
        'Verbose', true, ...
        'Plots', 'training-progress', ...
        'ExecutionEnvironment', 'auto');

    %% Train the Model
    disp('Starting model training...');
    [trainedModel, trainInfo] = trainnet(dataTrain, model, 'mse', options);

    disp('Model training complete.');
end
